version: '3'
services:
  website:
    container_name: website
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile
    restart: always
    env_file: ./apps/website/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    container_name: server
    build:
      context: .
      dockerfile: ./apps/server/Dockerfile
    restart: always
    env_file: ./apps/server/.env
    ports:
      - "3001:3001"
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres-db-volume:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - postgres-db-network
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'password'
    ports:
      - "16543:80"
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    networks:
      - postgres-db-network

volumes:
  postgres-db-volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ./data
networks:
  postgres-db-network:
    driver: bridge

