version: '3'
services:
  website:
    container_name: hewego_website
    build:
      context: .
      dockerfile: ./apps/website/Dockerfile
    restart: always
    env_file: ./apps/website/.env
    ports:
      - "3000:3000"
    depends_on:
      - api
  api:
    container_name: hewego_server
    build:
      context: ./apps/server
      dockerfile: ./Dockerfile
    restart: always
    env_file: ./apps/server/.env
    ports:
      - "3001:3001"
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dev_hedera
    ports:
      - "54325:5432"
    volumes:
      - postgres-db-volume:/data/postgres

volumes:
  postgres-db-volume:

